framework:
    secret:          secret
    router:          { resource: "%kernel.root_dir%/routing.yml" }
    form:            true
    csrf_protection: true
    templating:      { engines: ['twig'] }
    test:            ~
    session:
        storage_id: session.storage.filesystem

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
