framework:
    secret:          secret
    router:          { resource: "%kernel.root_dir%/routing.yml" }
    form:            true
    csrf_protection: true
    templating:      { engines: ['twig'] }
    test:            ~
    session:
        storage_id: session.storage.filesystem

# Mandango Configuration
mandango:
    logging:            %kernel.debug%
    default_connection: default
    connections:
        default:
            server: mongodb://localhost:27017
            database: pablodip_module_bundle

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
